// app/routes/api.ar-model.file.$name.tsx
// Serves the cached GLB files generated by api.ar-model.tsx

import type { LoaderFunctionArgs } from "@remix-run/node";
import * as fs   from "fs";
import * as path from "path";

const CACHE_DIR = process.env.GLB_CACHE_DIR || "/tmp/ar-models";

export async function loader({ params }: LoaderFunctionArgs) {
  const name    = params.name || "";
  const glbPath = path.join(CACHE_DIR, name);

  // Security: only allow .glb files, no path traversal
  if (!name.endsWith(".glb") || name.includes("/") || name.includes("..")) {
    return new Response("Not found", { status: 404 });
  }

  if (!fs.existsSync(glbPath)) {
    return new Response("Model not found", { status: 404 });
  }

  const buffer = fs.readFileSync(glbPath);

  return new Response(buffer, {
    headers: {
      "Content-Type":                "model/gltf-binary",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control":               "public, max-age=86400",
      "Content-Length":              String(buffer.length),
    },
  });
}
